pub fn match_block(name: &str) -> u32 {
    match name {
        "minecraft:stone" => 25,
        "minecraft:granite" => 26,
        "minecraft:polished_granite" => 27,
        "minecraft:diorite" => 28,
        "minecraft:polished_diorite" => 29,
        "minecraft:andesite" => 30,
        "minecraft:polished_andesite" => 31,
        "minecraft:deepslate" => 32,
        "minecraft:cobbled_deepslate" => 33,
        "minecraft:polished_deepslate" => 34,
        "minecraft:calcite" => 35,
        "minecraft:tuff" => 36,
        "minecraft:dripstone_block" => 37,
        "minecraft:grass_block" => 38,
        "minecraft:dirt" => 39,
        "minecraft:coarse_dirt" => 40,
        "minecraft:podzol" => 41,
        "minecraft:rooted_dirt" => 42,
        "minecraft:mud" => 43,
        "minecraft:crimson_nylium" => 44,
        "minecraft:warped_nylium" => 45,
        "minecraft:cobblestone" => 46,
        "minecraft:oak_planks" => 47,
        "minecraft:spruce_planks" => 48,
        "minecraft:birch_planks" => 49,
        "minecraft:jungle_planks" => 50,
        "minecraft:acacia_planks" => 51,
        "minecraft:dark_oak_planks" => 52,
        "minecraft:mangrove_planks" => 53,
        "minecraft:crimson_planks" => 54,
        "minecraft:warped_planks" => 55,
        "minecraft:oak_sapling" => 56,
        "minecraft:spruce_sapling" => 57,
        "minecraft:birch_sapling" => 58,
        "minecraft:jungle_sapling" => 59,
        "minecraft:acacia_sapling" => 60,
        "minecraft:dark_oak_sapling" => 61,
        "minecraft:mangrove_propagule" => 62,
        "minecraft:sand" => 63,
        "minecraft:red_sand" => 64,

        _ => 9999,
    }
}
